/*CREATE TABLE Cliente_Genero (
    cliente_genero_id INT PRIMARY KEY IDENTITY (1, 1),
    cod_genero VARCHAR (3) NOT NULL,
    descripcion VARCHAR (15) NOT NULL
); */


/*INSERT INTO Cliente_genero (cod_genero, descripcion) 
VALUES 
('M',	'MASCULINO'),
('F',	'FEMENINO'),
('J',	'JURIDICO')*/

select * from cliente_genero


/*CREATE TABLE MONEDA (
    MONEDA_ID INT PRIMARY KEY IDENTITY (1, 1),
	COD_MONEDA VARCHAR (8) NOT NULL,
    DESCRIPCION VARCHAR (15) NOT NULL,
	COTIZACION DECIMAL
); */

/*INSERT INTO MONEDA (COD_MONEDA, DESCRIPCION, COTIZACION) 
VALUES 
('PYG',	'GUARANIES',	'1'),
('USD',	'DOLARES',	'6980')*/

select * from MONEDA

/*CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY IDENTITY (1, 1),
    COD_CLIENTE VARCHAR (50) NOT NULL,
    NOMBRE_CLIENTE VARCHAR (100) NOT NULL,
    TIPO_PERSONA VARCHAR (20) NOT NULL,
    GENERO VARCHAR (2),
    FECHA_NACIMIENTO DATE,
	LOCALIDAD VARCHAR (50),
	FECHA_ALTA_CLIENTE DATE);*/

SELECT * FROM CLIENTES


/*CREATE TABLE PRODUCTOS (
    PRODUCTO_ID INT PRIMARY KEY IDENTITY (1, 1),
    OPERACION VARCHAR (50) NOT NULL,
    COD_CLIENTE VARCHAR (50) NOT NULL,
	MONEDA VARCHAR (8),
	TIPO_CARTERA VARCHAR (50),
	SALDO_CAPITAL DECIMAL,
	SALDO_INTERES DECIMAL,
    FECHA_PROCESO DATE,
	FECHA_VENCIMIENTO DATE);*/

select * from cliente_genero
select * from MONEDA
SELECT * FROM CLIENTES
SELECT * FROM PRODUCTOS

